version: "3"

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql8
    environment:
      PMA_HOST: mysql8
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - ./app-configs/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    # restart: always
    # ports:
    #     - 8081:80
    networks:
      - $DEFAULT_NETWORK
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$DEFAULT_NETWORK"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.$MY_DOMAIN`)"
      # - "traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt"

networks:
  $DEFAULT_NETWORK:
    external: true